### ISSUE TITLE
Non-ItemScheme MD queries not generated correctly

### ISSUE THREAD

**Issue by Tzaphkiel** [sosna/sdmx-rest4js#43]
Requestion dataflow metadata for example adds a 4th parameter to the URL that should only be present for `ItemSchemes`.

```js
var sdmxrest = require('sdmx-rest')
var ws = sdmxrest.getService({url: "http://--someEndPointNotPredefined--/service/"})
var query = {resource: "dataflow", detail: "allstubs"}
console.log("Query: "+ sdmxrest.getUrl(query, ws))
```
outputs:

> http://--someEndPointNotPredefined--/dataflow/all/all/latest/**_all_**?detail=allstubs&references=none

**Comment by Tzaphkiel** [comment]
The bug is actually only visible when not using a pre-defined WS (such as `ECB`) as  can be seen here:
[API version test](https://github.com/sosna/sdmx-rest4js/blob/master/src/utils/url-generator.coffee#L32)

Checking for an `ItemScheme` could/should be added to this `if`...

**Comment by sosna** [comment]
Should probably add a call to isItemScheme defined in [metadata-type](https://github.com/sosna/sdmx-rest4js/blob/master/src/metadata/metadata-type.coffee)

**Comment by Tzaphkiel** [comment]
Sounds good. Not knowing the code I would have added a new method in [validators](https://github.com/sosna/sdmx-rest4js/blob/master/src/utils/validators.coffee#L38)

**Comment by sosna** [comment]
Closed. Thanks for the fix @Tzaphkiel :)!
