### ISSUE TITLE
Programatically list the available/supported services

### ISSUE THREAD

**Issue by Tzaphkiel** [sosna/sdmx-rest4js#53]
It would be great for an application using this library to be able to present the user with a drop-down menu of the available/supported services.

If I'm not mistaken, currently the `Service` class has constants defining the individual services but nowhere is an array of them available.

**Comment by sosna** [comment]
Thanks for the feedback. The API now offers an array, with the list of known services (see [wiki for details](https://github.com/sosna/sdmx-rest4js/wiki/Services)).
