### ISSUE TITLE
Doc: wiki service page not up to date

### ISSUE THREAD

**Issue by Tzaphkiel** [sosna/sdmx-rest4js#54]
I see on this [wiki page](https://github.com/sosna/sdmx-rest4js/wiki/Services) that a few of the services defined in the [code](https://github.com/sosna/sdmx-rest4js/blob/master/src/service/service.coffee) are not described.

This [Where is it used](https://github.com/sdmx-twg/sdmx-rest/wiki/Where-is-it-used) page can help get the descriptive content for the still undefined services.

**Comment by sosna** [comment]
Thanks. The Wiki page has been updated.
