### ISSUE TITLE
Provide http response headers

### ISSUE THREAD

**Issue by sosna** [sosna/sdmx-rest4js#85]
The library offers the possibility to execute a request.

However, only the response body is returned by the function call.

It should however be possible for a client to get access to the full response, i.e. including headers.

Thanks to @Tzaphkiel for the proposal.

**Comment by sosna** [comment]
@Tzaphkiel the feature has been implemented (cf. the develop branch).

In a nutshell:
* `request` works as previously, i.e. only the body of the response gets returned;
* `request2` has been added to the API. It returns the full response (status, headers, body).

Adding a new function was the easiest option (considering the use of splats in the function definition and the willingness to keep the function definition simple from the client's perspective).

Unless you have any comment about the above, I'll release the new version tomorrow.

**Comment by Tzaphkiel** [comment]
That sounds acceptable.
Thank you !
