### ISSUE TITLE
Offer a list of valid resources for an api version

### ISSUE THREAD

**Issue by sosna** [sosna/sdmx-rest4js#86]
The list of supported resources vary with the version of the SDMX RESTful API. Version 1.3.0 for example adds a few new resources such as `actualconstraint` and `allowedconstraint` for example.

It would be nice if the library could offer a function returning the list of valid resources per API version.

Thanks to @Tzaphkiel for the proposal.

**Comment by sosna** [comment]
@Tzaphkiel, is the requirement to list all resources in general, or only the structural metadata-related ones?

I'm asking because the `data` resource (since v1.0.0) as well as the `availableconstraint` one (since v1.3.0) are "hidden" in the DataQuery and the AvailabilityQuery objects respectively.

So, the only place where I think the request applies, is for the `resource` property of the MetadataQuery object. Is that indeed what you had in mind? If so, I will focus on the structural metadata-related resources only.

Thanks!

**Comment by Tzaphkiel** [comment]
The idea is to be able to see what is supported for a specific version of the API.
I was however initially thinking of only the structural metadata-related ones.

Now that you mention it, It would be useful to list all the kind of resources available in the specific version of the API. If that is done, then I would somehow qualify them in two categories: Data & Metadata.

**Comment by sosna** [comment]
@Tzaphkiel The feature has been [implemented](https://github.com/sosna/sdmx-rest4js/commit/0581cadb6987077e6a815fbd56e47c3ccdc020a2) in the `develop` branch and will be part of the next release (hopefully this week-end).

The Wiki has been updated accordingly.
