### ISSUE TITLE
Calling request triggers a TypeError

### ISSUE THREAD

**Issue by sosna** [sosna/sdmx-rest4js#87]
Executing the following query on a Mac triggers a `TypeError`

```javascript
sdmxrest.request("http://sdw-wsrest.ecb.europa.eu/service/data/EXR/A.CHF.EUR.SP00.A")
     .then(function(data) {console.log(data);})
     .catch(function(error) {console.log(error);});
```
The error is:
```javascript
url.js:87
    throw new TypeError('Parameter "url" must be a string, not ' + typeof url);
    ^

TypeError: Parameter "url" must be a string, not object
    at Url.parse (url.js:87:11)
    at Object.urlParse [as parse] (url.js:81:5)
```
Thanks to @stratosn for reporting the issue.

**Comment by stratosn** [comment]
Hi @sosna, 

If you need the full stack trace, please let me know.

**Comment by sosna** [comment]
That would be great, thanks!

**Comment by sosna** [comment]
Hi @stratosn,
If you have a bit of spare time, would you mind posting the stacktrace? I have a bit of time to work on this :).
Thanks!

**Comment by stratosn** [comment]
Hi @sosna , I tried to reproduce it, but unfortunately failed. 
Sorry for that, maybe you may close it for the moment and if I manage to reproduce it, I will post back on this issue.

**Comment by sosna** [comment]
Thanks, @stratosn, I'll close it for the time being then.
